restaurant_menu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MenuList.as_view(), name='home'),
    path('item/<int:pk>/', views.MenuItemDetail.as_view(), name='menu_item'),
]

restaurant_menu/models.py
from django.db import models
from django.contrib.auth.models import User

MEAL_TYPE = (
    ("starters", "Starters"),
    ("salads", "Salads"),
    ("main_dishes", "Main Dishes"),
    ("desserts", "Desserts")
)

STATUS = (
    (0, 'Unavailable'),
    (1, 'Available')
)


# Create your models here.
class Item(models.Model):
    meal = models.CharField(max_length=1000, unique=True)
    description = models.CharField(max_length=2000)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    meal_type = models.CharField(max_length=200, choices=MEAL_TYPE)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    status = models.IntegerField(choices=STATUS, default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.meal

restaurant_menu/views.py
from django.shortcuts import render
from django.views import generic
from .models import Item, MEAL_TYPE


# Create your views here.
class MenuList(generic.ListView):
    queryset = Item.objects.order_by('-date_created')
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['meals'] = MEAL_TYPE

        return context


class MenuItemDetail(generic.DetailView):
    model = Item
    template_name = 'menu_item_detail.html'

restaurant_menu/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Menu home</h1>
    {% for meal in meals %}
    <h2>{{ meal.1 }}</h2>
        {% for row in item_list %}
            {% if row.meal_type == meal.0 %}
                {% if row.status == 0 %}
                <a href="{% url 'menu_item' row.pk %}"><h3><del>{{ row.meal }}</del></h3></a>
                <p>{{ row.description }}</p>
                {% else %}
                <a href="{% url 'menu_item' row.pk %}"><h3>{{ row.meal }}</h3></a>
                <p>{{ row.description }}</p>
                {% endif %}
            {% endif %}
        {% endfor %}
    {% endfor %}
</body>
</html>

restaurant_menu/templates/menu_item_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ item.meal }}</h1>
    <p>{{ item.description }}</p>
    <p>{{ item.price }}</p>
</body>
</html>